add_files -norecurse -scan_for_includes $PANDA_WRAP
add_files -norecurse -scan_for_includes $RISCV_CORE
add_files -norecurse -scan_for_includes $MEMORY
add_files -norecurse -scan_for_includes $APB
add_files -norecurse -scan_for_includes $LSU
add_files -norecurse -scan_for_includes $CACHE
add_files -norecurse -scan_for_includes $WISHBONE
add_files -norecurse -scan_for_includes $COMMON
add_files -norecurse -scan_for_includes $DBG_MODULE
add_files -norecurse -scan_for_includes $UART_MODULE
add_files -norecurse -scan_for_includes $TIMER_MODULE
add_files -norecurse -scan_for_includes $GPIO_MODULE